# Generated by Django 3.0.5 on 2020-04-17 13:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200417_1200'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('works', django.db.models.manager.Manager()),
            ],
        ),
    ]
